### ISSUE TITLE
How you generate the ground truth

### ISSUE THREAD

**Issue by Jarrome** [MaaniGhaffari/incremental_gpom#1]
Hi, I really want to know how you generate the ground truth in the paper.

**Comment by MaaniGhaffari** [comment]
Are you referring to the results in Section 3.5?

From the paper, **Section 3.5**:
"The ground truth map was generated using the registered points map and an image dilation technique
to remove outliers. In this way, the ground truth map has the same orientation which makes the comparison convenient. GPOM-based maps infer partially observed regions; however, **in the absence of a complete ground truth map**, this fact can be only verified using Fig. 5 and is not reflected in the AUC of I-GPOM and I-GPOM2."

So I'm relying on the SLAM's estimated trajectory to come up with a proxy to the ground truth map as I don't have access to it. Later in the exploration, the ground truth is available since it's a simulation.

**Comment by Jarrome** [comment]
Yes, on the real arena. 

Ok, I will attempt to repeat your words. With SLAM, we can achieved the revised pose. And then filter out some outliers. We utilize the revised pose for both training and ground truth while for the range data, we gonna take non-filtered for training, and filtered on ground truth.

**Comment by MaaniGhaffari** [comment]
Make sure your SLAM results are correct and consistent. The maps assume known robot poses, so the comparison of mapping techniques relative to the SLAM results is still valid.

**Comment by Jarrome** [comment]
Great, thx.
